### ISSUE TITLE
Not attaching token to outgoing requests

### ISSUE THREAD

**Issue by DevarshiDave** [AlbanyInternationalCorp/Adal-Angular-TS#12] opened 2018-01-30 09:46 UTC
Hi,

I am using this library in my IONIC 3 app to call sharepoint rest api, it logs me in successfully, but after that when i call the api, i get 403 forbidden error and my request doesnt have the bearer token attached in the header.

Help please!

**Comment by Only1MrAnderson** [comment] 2018-01-30 14:09
Are you using the `HttpClient` from angular for the rest call?

**Comment by DevarshiDave** [comment] 2018-01-30 14:13
yes, the `HTTP_INTERCEPTOR` class is in `HttpClient` so i had to use that only. but it didnt attach token.

**Comment by Only1MrAnderson** [comment] 2018-01-30 14:16
Can you provide a project that reproduces this error so I can test?

**Comment by DevarshiDave** [comment] 2018-01-30 14:17
alright, should i create a repo or just attach a zip file over here?

**Comment by Only1MrAnderson** [comment] 2018-01-30 14:17
A repo is fine.

**Comment by DevarshiDave** [comment] 2018-01-31 08:23
Hi, sorry for the delay,
Here is the link to my repo [ionic-demo](https://github.com/DevarshiDave/ionic-with-angular-adal-ts)

In **app.module.ts** i have defined the `adalConfig `variable.
For the demo to work you need to configure the app with your` app id` and `sharepoint rest urls`.

**Quick Guide**
Default route is the home route,
Inside the Home page, there is one button 'View Details' that will navigate you to **itemDetails** route.
There are 2 buttons in **itemDetails** route, 

1. Login

2. Get SP List Data

You can test the code in the itemDetails route.

**Comment by ricetristan** [comment] 2018-01-31 17:41
@Only1MrAnderson  I'm wondering if this has to do with the availability of sessionStorage inside of Ionic apps? I don't see any reference to sessionStorage in the Ionic storage docs...

**Comment by Only1MrAnderson** [comment] 2018-02-01 14:04
@DevarshiDave We believe we have resolved the issue, please go ahead and bump your version to `1.1.5`.

**Comment by Only1MrAnderson** [comment] 2018-02-06 20:27
@DevarshiDave After a successful login, is the browser with the token in the URL closing for you? How are you handling that?

**Comment by Only1MrAnderson** [comment] 2019-04-08 19:42
I am closing this issue due to inactivity.

**Closed as completed by Only1MrAnderson** 2019-04-08 19:42 UTC

**Comment by DevarshiDave** [comment] 2019-04-09 06:18
I was actually using the wrong sdk for my project, since my ionic app is a native app and not a web app, i had to use the 

> cordova-plugin-ms-adal

Also by downloading the [typescript library](https://ionicframework.com/docs/native/ms-adal) provided by Ionic team, i got my project working.
